name: "Terraform Automation"

on:
  push:
    branches:
      - main # run when code is pushed to main
  pull_request: # run when someone wants to merge code

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_database_API_KEY: ${{ secrets.TF_VAR_database_API_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: ~/devops/infrastructure/04_modules/projects/marketing

      - name: Terraform plan
        run: terraform plan
        working-directory: ~/devops/infrastructure/04_modules/projects/marketing

      - name: Terraform Apply
        if: github.ref == 'ref/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ~/devops/infrastructure/04_modules/projects/marketing